### ISSUE TITLE
[1.18.2] AoF5 & OwO (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by andrewscouten** [wisp-forest/owo-velocity-plugin#1]
## Issue
I am trying to connect to an All of Fabric 5 v1.3.1 (1.18.2 Minecraft) server from a Velocity proxy (with legacy forwarding, using FabricProxy and CrossStitch). OwO is installed on both the server and proxy side. Whenever I try to connect I get an ArrayIndexOutOfBounds exception, and upon investigation I determined this plugin to be the issue.

## Solution(?)
I fixed this issue myself by changing [`OwoHandshakeHandler#onPreLogin(PreLoginEvent event)`](https://github.com/wisp-forest/owo-velocity-plugin/blob/master/src/main/java/me/basiqueevangelist/owovelocity/OwoHandshakeHandler.java#L30) from:

```java
conn.sendLoginPluginMessage(OwoVelocityPlugin.HANDSHAKE_ID, new byte[0], responseBody -> {
```
To:
```java
conn.sendLoginPluginMessage(OwoVelocityPlugin.HANDSHAKE_ID, new byte[Short.MAX_VALUE / 4], responseBody -> {
```

After changing this and recompiling, my connection can now be established. I did not make this a PR, as I honestly have no idea the ramifications of doing it this way (how it would affect other MC versions, etc.), but this is how I fixed that issue in this specific case.

**Comment by BasiqueEvangelist** [comment]
Fixed in `0.1.1`. Thanks for the report!
