### ISSUE TITLE
I suppose your plugin is kill at least for Velocity 3.3.0

### ISSUE THREAD

**Issue by Neubulae** [wisp-forest/owo-velocity-plugin#3]
PaperMC/Velocity/pull/1202

**Comment by BasiqueEvangelist** [comment]
That PR doesn't seem like it'd affect this plugin :thinking:

Regardless, the plugin shouldn't be needed due to the switch to configuration (and handshake being disabled in prod)

**Comment by Neubulae** [comment]
> That PR doesn't seem like it'd affect this plugin 🤔
> 
> Regardless, the plugin shouldn't be needed due to the switch to configuration (and handshake being disabled in prod)

ok cool im not kill thx
